format_version: 10
pipelines:
  expense-tf-apply:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/iteration2-chaitu/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VARS_vault_token: AES:LTkBf3BKEEsyD2bewXdVBg==:BiRlI4E6w2gjPPYxQcOLHGnOkVjKrXUP+uY1QzzS4f8=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-var-file=env-dev/main.tfvars"  "-var=vault_token=$TF_VAR_vault_token", "-auto-approve" ], run_if: passed}

#     - PROD:
#         fetch_materials: true
#         environment_variables:
#           env: prod
#         approval:
#           type: success
#         jobs:
#           terraform-apply:
#             tasks:
#             - exec: {command: terraform, arguments: [ "init", "-backend-config=env-prod/state.tfvars" ], run_if: passed}
#